#ifndef AXTP_STATUS_H
#define AXTP_STATUS_H

typedef enum {
  AXTP_STATUS_OK = 0,
  AXTP_STATUS_INVALID_ARGUMENT = 1,
  AXTP_STATUS_NO_MEMORY = 2,
  AXTP_STATUS_NOT_FOUND = 3,
  AXTP_STATUS_TIMEOUT = 4,
  AXTP_STATUS_QUEUE_FULL = 5,
  AXTP_STATUS_DECODE_ERROR = 6
} axtp_status_t;

#endif
