#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
spec="${AXTP_SPEC_PATH:-$root/third_party/axtp-spec}"

if [[ ! -d "$spec/registry" ]]; then
  echo "AXTP_SPEC_PATH must point to an AXTP spec checkout with registry/." >&2
  echo "Current value: $spec" >&2
  exit 1
fi

if [[ ! -f "$root/generators/dist/sourceLoader.js" ]]; then
  echo "Generator is not built. Run: pnpm --dir generators build" >&2
  exit 1
fi

AXTP_RUNTIME_ROOT="$root" AXTP_SPEC_ROOT="$spec" node --input-type=module <<'NODE'
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.env.AXTP_RUNTIME_ROOT;
const specRoot = process.env.AXTP_SPEC_ROOT;

const { loadProtocolSources } = await import(pathToFileURL(path.join(root, "generators/dist/sourceLoader.js")).href);
const { validateSpec } = await import(pathToFileURL(path.join(root, "generators/dist/validator.js")).href);

const spec = await loadProtocolSources(specRoot);
for (const message of validateSpec(spec)) console.log(message);

const outDir = path.join(root, "include/generated");
await mkdir(outDir, { recursive: true });

function cName(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
}

function hex(id, width = 4) {
  return `0x${id.toString(16).toUpperCase().padStart(width, "0")}`;
}

function enumDefines(prefix, items, width) {
  return [...items]
    .sort((lhs, rhs) => lhs.id - rhs.id)
    .map((item) => `#define ${prefix}_${cName(item.name)} ${hex(item.id, width)}`)
    .join("\n");
}

const ids = `/* Generated by axtp-c-runtime generator. Do not edit manually. */
#ifndef AXTP_IDS_GENERATED_H
#define AXTP_IDS_GENERATED_H

#include <stdint.h>

${enumDefines("AXTP_PAYLOAD_TYPE", spec.payloadTypes, 2)}

${enumDefines("AXTP_CONTROL_OPCODE", spec.controlOpcodes, 2)}

${enumDefines("AXTP_RPC_ENCODING", spec.rpcEncodings, 2)}

${enumDefines("AXTP_RPC_BODY_ENCODING", spec.rpcBodyEncodings, 2)}

${enumDefines("AXTP_RPC_OP", spec.rpcOps, 2)}

${enumDefines("AXTP_METHOD_ID", spec.methods, 4)}

${enumDefines("AXTP_EVENT_ID", spec.events, 4)}

${enumDefines("AXTP_ERROR_CODE", spec.errors, 4)}

${enumDefines("AXTP_CAPABILITY_ID", spec.capabilities, 4)}

#endif
`;

const methodRows = [...spec.methods]
  .sort((lhs, rhs) => lhs.id - rhs.id)
  .map((item) => `  { ${hex(item.id)}, "${item.name}", "${item.domain}", "${item.requestSchema}", "${item.responseSchema}" },`)
  .join("\n");
const eventRows = [...spec.events]
  .sort((lhs, rhs) => lhs.id - rhs.id)
  .map((item) => `  { ${hex(item.id)}, "${item.name}", "${item.domain}", "${item.eventSchema}" },`)
  .join("\n");

const registry = `/* Generated by axtp-c-runtime generator. Do not edit manually. */
#ifndef AXTP_REGISTRY_GENERATED_H
#define AXTP_REGISTRY_GENERATED_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
  uint16_t id;
  const char* name;
  const char* domain;
  const char* request_schema;
  const char* response_schema;
} axtp_method_descriptor_t;

typedef struct {
  uint16_t id;
  const char* name;
  const char* domain;
  const char* event_schema;
} axtp_event_descriptor_t;

static const axtp_method_descriptor_t AXTP_METHOD_REGISTRY[] = {
${methodRows}
};

static const size_t AXTP_METHOD_REGISTRY_COUNT = ${spec.methods.length};

static const axtp_event_descriptor_t AXTP_EVENT_REGISTRY[] = {
${eventRows}
};

static const size_t AXTP_EVENT_REGISTRY_COUNT = ${spec.events.length};

#endif
`;

await writeFile(path.join(outDir, "axtp_ids_generated.h"), ids);
await writeFile(path.join(outDir, "axtp_registry_generated.h"), registry);
console.log(`[OK] generated C artifacts: ${outDir}`);
NODE
